[tool.commitizen]
version = "1.0.2"
bump_message = "chore(release): $current_version -> $new_version [skip-ci]"
version_files = [
    "StreamerBotPlugin/Properties/AssemblyInfo.cs",
]
tag_format = "v$version"